apiVersion: v1
kind: Service
metadata:
#  名字叫做 mysql，你也可以随便换
  name: webook-mysql
spec:
#  方便我们调试
  #type: LoadBalancer
  type: NodePort
  ports:
#    避免冲突，我用了 3308 端口
    - port: 3308
      name: mysql
      nodePort: 31380
      protocol: TCP
      targetPort: 3306
# 筛选带 app:mysql 的 pod
  selector:
    app: webook-mysql
