# 准备暴露出去给外面用
apiVersion: v1
kind: Service
metadata:
  name: webook-redis
spec:
#  船新的 NodePort 类型
#  type: NodePort
  type: NodePort
  selector:
    app: webook-redis
  ports:
    - port: 6380
#      外部访问的端口，必须是 30000-32767 之间
      nodePort: 31379
#      pod 暴露的端口
      targetPort: 6379
