# 开始描述 mysql 的存储结构需要具备什么样的特征
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-pv-claim
spec:
#  这里的 manual 其实是一个我们自己写的，只是用来绑定一下 pv 而已
  storageClassName: manual
#  访问模式，这里主要是控制能不能被多个 pod 读写
  accessModes:
# 被一个 pod 读写
    - ReadWriteOnce
# 究竟需要一些什么资源
  resources:
    requests:
#      需要一个 G 的容量
      storage: 1Gi
